FROM tomcat:9-jdk11-corretto

LABEL maintainer="tarigor80@gmail.com"

ADD epam-java-web-development-course-final-task_war.war /usr/local/tomcat/webapps/

EXPOSE 8085

CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]
