version: '3.3'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_vol:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: 12345678
       MYSQL_DATABASE: hotel_db
       MYSQL_USER: administrator
       MYSQL_PASSWORD: 12345678
     ports:
       - 3307:3306
   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
   web:
    build:
      context: .       
    depends_on:
      - db
    image: tomcat:9-jdk11-corretto
    volumes:
      - ./epam-java-web-development-course-final-task_war.war:/usr/local/tomcat/webapps/ROOT.war
    ports:
      - '8085:8080'
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: hotel_DB
      MYSQL_USER: administrator
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_HOST: 172.18.0.1
volumes:
    db_vol: 
