package com.epam.hotel.service.factory;

public enum ServiceType {
    COMMON_SITE_ACTIVITY_SERVICE,
    DATABASE_CONNECTION_SERVICE,
    PROPERTIES_FILE_SERVICE,
    REUSABLE_POOL_SERVICE,
    CLIENT_SERVICE,
    ROOM_SERVICE;
}
